[package]
name = "tmi-sys"
version = "0.1.0"
authors = ["Szymon Walter <waltersz@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53"

[[example]]
name = "bot"
path = "examples/bot.rs"
crate_type = ["cdylib"]
